<html>
    <body>

     <h1> Page Directives </h1>

        1. Use Import Directive
        <%@ page import="java.util.Date" %> <br>

           Today is <% int date =  new Date().getDate();
             out.println(date);
         %>

         2. Page ContentType
         <%@ page contentType="application/msword"; %>

           3. extends Attribute
         	This attribute defines the parent class that will be inherited by the generated servlet. It is rarely used.

 	4. Info Attribute
   	The attribute simply sets the information of the JSP page which is retrieved later by using getServletInfo() method of Servlet interface.

	<% page info="composed by Mayank Dembla"; %>

	The Web Container will create a method getServletInfo() in the resulting servlet.

	Eg.
	Public String getServletInfo()
	{
		Return "composed by Mayank Dembla" ;
	}


		5. Buffer Attribute
    	The buffer attribute sets the buffer size in kb to handle the output generated by the JSP Page. Default Size is 8kb.
		<% page buffer="16kb" %>

    	6. Language Attribute
    	The Language attribute specifies the scripting language used in the JSP page. The default value is "java".

    	7. isELIgnored Attribute
        We can ignore the Expression Language (EL) in the jsp by the isELIgnored attribute. By default its value is False i.e. Expression language is enabled by default.
        <%@ page isELIgnored="true" %>

       8. isThreadSafe Attribute
	Servlets and JSP, both are multithreaded.
	If you want to control the behavior of  JSP page, you can use the isThreadSafe attribute
	The value of isThreadSafe is true.

	If you make it false, the web container will serialize the multiple requests, i.e. it will wait until JSP finishes responding to a request before passing another request to it.

	<%@ page isThreadSafe='false' %>

	The Web Container in such a case, will generate the servlet as:

	Public class SimplePage_jsp extends HttpJspBase implements SingleThreadMode{
	….
     }

     9. errorPage Attribute
	The errorPage attribute is used to define the error page. If exception occurred in the current page, it will redirect it to the error page.

	<%@ page errorPage="implicitobjects/showerror.jsp" %>

    10. isErrorPage attribute
	The isErrorPage attribute is used to declare that the current page is of error page.

        <%@ page isErrorPage="true" %>

    </body>
</html>
